# Generated by Django 5.2.7 on 2026-06-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinechecklistitem',
            name='comment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routinechecklistitem',
            name='photo_required',
            field=models.BooleanField(default=False),
        ),
    ]
