# Generated by Django 5.2.7 on 2026-06-09 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_routinechecklistitem_comment_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineexecution',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routine.routineschedule'),
        ),
    ]
