# Generated by Django 5.2.7 on 2026-06-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_alter_routineexecution_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexecution',
            name='execution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routineexecution',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
