# Generated by Django 5.2.7 on 2026-06-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_routineexecution_execution_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexecution',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
