# Generated by Django 5.2.7 on 2026-02-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
