# Generated by Django 5.2.7 on 2026-05-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_test', '0003_rename_branch_number_employee_branch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('INDUCTION_TRAINING', 'Induction Training'), ('ROLE_BASED_TRAINING', 'Role Based Training'), ('EXTERNAL_TRAINING', 'External Training')], default='INDUCTION_TRAINING', max_length=50),
        ),
    ]
