# Generated by Django 5.2.7 on 2026-05-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_test', '0004_test_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='training_type',
            field=models.CharField(blank=True, choices=[('CLASSROOM', 'Classroom'), ('ONLINE', 'Online'), ('VIDEO_BASED', 'Video Based'), ('SELF_LEARNING', 'Self Learning'), ('PRESENTATION', 'Presentation'), ('DEMONSTRATION', 'Demonstration'), ('PRACTICAL', 'Practical'), ('ON_THE_JOB', 'On The Job'), ('QUALITY', 'Quality'), ('TECHNICAL_CERTIFICATION', 'Technical Certification'), ('AWARENESS', 'Awareness')], max_length=100, null=True),
        ),
    ]
