# Generated by Django 5.2.7 on 2026-04-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [

        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('STAGE_SUBMITTED', 'Stage Submitted'), ('STAGE_MOVED', 'Stage Moved'), ('FORM_MOVED', 'Form Moved'), ('MOVE', 'Move Stage'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
