# Generated by Django 5.2.7 on 2026-03-07 05:55

import project_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=project_management.models.task_document_upload_path),
        ),
        migrations.AddField(
            model_name='task',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
