# Generated by Django 5.2.7 on 2026-06-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_no', models.CharField(max_length=100, unique=True)),
                ('date_received', models.DateField()),
                ('received_by', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_contact', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('product_name', models.CharField(max_length=255)),
                ('part_number', models.CharField(max_length=255)),
                ('lot_batch_number', models.CharField(max_length=255)),
                ('sales_order_no', models.CharField(max_length=255)),
                ('feedback_type', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=255)),
                ('source_of_feedback', models.CharField(max_length=255)),
                ('reference_document', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback/')),
                ('date_of_occurrence', models.DateField(blank=True, null=True)),
                ('location_site', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('impact_on_customer', models.CharField(blank=True, max_length=255, null=True)),
                ('immediate_action_taken', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('target_investigation_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('notify_users', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
