# Generated by Django 5.2.7 on 2026-06-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('CAPA Created', 'CAPA Created'), ('Response Sent', 'Response Sent'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('Complaint', 'Complaint'), ('Suggestion', 'Suggestion'), ('Appreciation', 'Appreciation'), ('Escalation', 'Escalation'), ('Delivery Issue', 'Delivery Issue'), ('Service Issue', 'Service Issue')], max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='lot_batch_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='part_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sales_order_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='source_of_feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
