# Generated by Django 5.2.7 on 2026-06-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0002_supplier_business_impact_supplier_compliance_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdocument',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
