# Generated by Django 5.2.7 on 2026-06-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0003_supplierdocument_document_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierevaluation',
            old_name='commercial_score',
            new_name='communication_score',
        ),
        migrations.RenameField(
            model_name='supplierevaluation',
            old_name='compliance_score',
            new_name='cost_score',
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='approval_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='corrective_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='next_evaluation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='qms_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='weak_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierevaluation',
            name='weighted_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
