# Generated by Django 5.2.7 on 2026-06-05 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0004_rename_commercial_score_supplierevaluation_communication_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAuditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_no', models.CharField(max_length=50, unique=True)),
                ('audit_type', models.CharField(choices=[('initial', 'Initial Supplier Audit'), ('surveillance', 'Surveillance Audit'), ('process', 'Process Audit'), ('pre_qualification', 'Pre-Qualification Audit'), ('system', 'System Audit'), ('special', 'Special Audit')], max_length=50)),
                ('audit_standard', models.CharField(default='ISO 9001:2015', max_length=100)),
                ('preferred_date', models.DateField()),
                ('reason', models.TextField()),
                ('objectives', models.TextField(blank=True, null=True)),
                ('departments', models.TextField(blank=True, null=True)),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='requested', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('audit_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('open_findings', models.IntegerField(default=0)),
                ('open_scar', models.IntegerField(default=0)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='supplier_audit_requests/')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_supplier_audits', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_supplier_audits', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_requests', to='sm.supplier')),
            ],
        ),
        migrations.DeleteModel(
            name='SupplierAudit',
        ),
    ]
