# Generated by Django 5.2.7 on 2026-06-05 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0005_supplierauditrequest_delete_supplieraudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierauditrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Supplier Audit Request', 'verbose_name_plural': 'Supplier Audit Requests'},
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='approval_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='audit_scope',
            field=models.TextField(blank=True, help_text='Selected audit areas', null=True),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='evaluation_score_snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='final_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supplier_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='result',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('conditional', 'Conditional Approval'), ('rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='review_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_supplier_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='risk_level_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplierauditrequest',
            name='audit_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='supplierauditrequest',
            name='open_findings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplierauditrequest',
            name='open_scar',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
