# Generated by Django 5.2.7 on 2026-06-05 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0006_alter_supplierauditrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='attachment',
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='approval_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='last_audit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='review_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierauditrequest',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierauditrequest',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SupplierAuditAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='supplier_audit_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('audit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='sm.supplierauditrequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
