# Generated by Django 5.2.7 on 2026-06-05 07:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0007_remove_supplierauditrequest_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditScopeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliverableMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='supplierauditrequest',
            options={},
        ),
        migrations.RenameField(
            model_name='supplierauditrequest',
            old_name='approval_comments',
            new_name='additional_notes',
        ),
        migrations.RenameField(
            model_name='supplierauditrequest',
            old_name='final_approver',
            new_name='approved_by',
        ),
        migrations.RenameField(
            model_name='supplierauditrequest',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='supplierauditrequest',
            old_name='preferred_date',
            new_name='preferred_audit_date',
        ),
        migrations.RenameField(
            model_name='supplierauditrequest',
            old_name='deliverables',
            new_name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='assigned_auditor',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='audit_no',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='audit_scope',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='audit_score',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='audit_standard',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='evaluation_score_snapshot',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='last_audit_date',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='open_findings',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='open_scar',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='result',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='review_comments',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='review_status',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='risk_level_snapshot',
        ),
        migrations.RemoveField(
            model_name='supplierauditrequest',
            name='scheduled_date',
        ),
        migrations.AddField(
            model_name='supplierauditattachment',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='audit_category',
            field=models.CharField(choices=[('onsite', 'On-site Audit'), ('remote', 'Remote Audit'), ('hybrid', 'Hybrid Audit')], default='onsite', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='audit_criteria',
            field=models.CharField(choices=[('iso9001', 'ISO 9001:2015'), ('iatf16949', 'IATF 16949'), ('iso13485', 'ISO 13485'), ('iso14001', 'ISO 14001'), ('iso45001', 'ISO 45001'), ('customer', 'Customer Requirement'), ('internal', 'Internal Supplier Standard')], default='iso9001', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='audit_trigger',
            field=models.CharField(choices=[('periodic', 'Periodic Audit'), ('complaint', 'Customer Complaint'), ('new_supplier', 'New Supplier Qualification'), ('performance', 'Poor Supplier Performance'), ('capa', 'CAPA Verification'), ('management', 'Management Decision'), ('regulatory', 'Regulatory Requirement')], default='periodic', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='current_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='request_no',
            field=models.CharField(default='SAR-2026-0001', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='requested_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='supplier_code_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierauditrequest',
            name='supplier_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplierauditattachment',
            name='file',
            field=models.FileField(upload_to='supplier_audits/'),
        ),
        migrations.AlterField(
            model_name='supplierauditrequest',
            name='audit_type',
            field=models.CharField(choices=[('initial', 'Initial Qualification Audit'), ('surveillance', 'Surveillance Audit'), ('requalification', 'Requalification Audit'), ('special', 'Special Audit'), ('followup', 'Follow-up Audit')], max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierauditrequest',
            name='objectives',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplierauditrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_audit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supplierauditrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('planned', 'Planned'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='SupplierAuditApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('planned', 'Planned'), ('closed', 'Closed')], max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('audit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='sm.supplierauditrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierAuditDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='sm.supplierauditrequest')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.deliverablemaster')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierAuditDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='sm.supplierauditrequest')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.departmentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierAuditScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='sm.supplierauditrequest')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.auditscopemaster')),
            ],
        ),
        migrations.DeleteModel(
            name='SupplierApproval',
        ),
    ]
