# Generated by Django 5.2.7 on 2026-06-18 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model_no', models.CharField(blank=True, max_length=100)),
                ('serial_no', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('range_specification', models.CharField(blank=True, max_length=255)),
                ('accuracy', models.CharField(blank=True, max_length=255)),
                ('calibration_frequency_days', models.PositiveIntegerField(default=365)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DUE', 'Calibration Due'), ('OVERDUE', 'Overdue'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('certificate_number', models.CharField(max_length=100)),
                ('calibration_agency', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='calibration/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='quality.instrument')),
            ],
            options={
                'ordering': ['-calibration_date'],
            },
        ),
    ]
