# Generated by Django 5.2.7 on 2026-06-18 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MSAStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msa_no', models.CharField(max_length=50, unique=True)),
                ('study_type', models.CharField(choices=[('GRR', 'Gauge R&R'), ('BIAS', 'Bias'), ('LINEARITY', 'Linearity'), ('STABILITY', 'Stability')], max_length=20)),
                ('study_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='MSAReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=100)),
                ('part_no', models.CharField(max_length=100)),
                ('trial_no', models.IntegerField()),
                ('measured_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='quality.msastudy')),
            ],
        ),
    ]
