# Generated by Django 5.2.7 on 2026-06-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_msastudy_msareading'),
    ]

    operations = [
        migrations.AddField(
            model_name='msastudy',
            name='grr_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='operator_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='part_count',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='part_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='study_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='trial_count',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
