# Generated by Django 5.2.7 on 2026-06-19 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_msastudy_grr_percentage_msastudy_operator_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='msastudy',
            name='study_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('CONDITIONAL', 'Conditional'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='SPCControlPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_no', models.CharField(max_length=50, unique=True)),
                ('part_number', models.CharField(max_length=100)),
                ('characteristic', models.CharField(max_length=255)),
                ('lsl', models.DecimalField(decimal_places=4, max_digits=12)),
                ('target', models.DecimalField(decimal_places=4, max_digits=12)),
                ('usl', models.DecimalField(decimal_places=4, max_digits=12)),
                ('sample_size', models.PositiveIntegerField(default=5)),
                ('frequency', models.CharField(default='Hourly', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quality.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='SPCReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_no', models.CharField(max_length=50)),
                ('measured_value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('reading_date', models.DateTimeField(auto_now_add=True)),
                ('control_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='quality.spccontrolplan')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
