# Generated by Django 5.2.7 on 2026-06-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_alter_msastudy_study_status_spccontrolplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='msastudy',
            name='operator_count',
        ),
        migrations.AddField(
            model_name='msastudy',
            name='operator_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='msareading',
            name='measured_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
