# Generated by Django 5.2.7 on 2026-06-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_remove_msastudy_operator_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msastudy',
            name='av',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='equipment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='equipment_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='ev',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='least_count',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='ndc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='part_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='pv',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='record_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='tolerance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='tv',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
