# Generated by Django 5.2.7 on 2026-06-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_msastudy_av_msastudy_equipment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='msastudy',
            name='percent_av',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='percent_ev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='percent_pv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='percent_rr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='msastudy',
            name='rr',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
