# Generated by Django 5.2.7 on 2026-06-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0007_msastudy_percent_av_msastudy_percent_ev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msastudy',
            name='av',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='msastudy',
            name='ev',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='msastudy',
            name='pv',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='msastudy',
            name='tv',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
