# Generated by Django 5.2.7 on 2026-06-23 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0008_alter_msastudy_av_alter_msastudy_ev_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSAPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='quality.msastudy')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
