# Generated by Django 5.2.7 on 2026-06-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_msapart'),
    ]

    operations = [
        migrations.AddField(
            model_name='msastudy',
            name='mean_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
