# Generated by Django 5.2.7 on 2026-06-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0010_msastudy_mean_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msastudy',
            name='equipment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='msastudy',
            name='equipment_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
