# Generated by Django 5.2.7 on 2026-02-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0001_initial'),
    ]

    operations = [
        
    ]
