# Generated by Django 5.2.7 on 2026-02-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0002_batchpart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='require_part_id',
            field=models.BooleanField(default=True),
        ),
    ]
