# Generated by Django 5.2.7 on 2026-02-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0003_form_require_part_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='require_part_id',
            field=models.BooleanField(default=False),
        ),
    ]
