# Generated by Django 5.2.7 on 2026-03-09 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0004_alter_form_require_part_id'),
    ]

    operations = [
        
    ]
