# Generated by Django 5.2.7 on 2026-03-09 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0005_customuser_account_locked_customuser_failed_attempts_and_more'),
    ]

    operations = [
        
    ]
