# Generated by Django 5.2.7 on 2026-03-09 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0005_customuser_account_locked_customuser_failed_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagehistory',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms_app.batchpart'),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='FinalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufactured_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='qms_app.batchpart')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('supplier', models.CharField(max_length=200)),
                ('lot_number', models.CharField(max_length=100)),
                ('received_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='batchpart',
            name='material_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms_app.materialbatch'),
        ),
        migrations.AddField(
            model_name='formbatch',
            name='material_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms_app.materialbatch'),
        ),
    ]
