# Generated by Django 5.2.7 on 2026-03-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0006_stagehistory_part_stagehistory_remarks_finalproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpageaccess',
            name='can_materialBatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_userdetail',
            field=models.BooleanField(default=False),
        ),
    ]
