# Generated by Django 5.2.7 on 2026-03-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0007_userpageaccess_can_materialbatch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formbatch',
            unique_together={('form', 'company_name', 'batch_id')},
        ),
    ]
