# Generated by Django 5.2.7 on 2026-03-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0008_alter_formbatch_unique_together'),
    ]

    operations = [
        
    ]
