# Generated by Django 5.2.7 on 2026-03-14 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0009_alter_batchpart_part_id'),
    ]

    operations = [
        
    ]
