# Generated by Django 5.2.7 on 2026-03-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0010_machinesession'),
    ]

    operations = [
        
    ]
