# Generated by Django 5.2.7 on 2026-03-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0011_alter_machinesession_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpageaccess',
            name='can_form_build',
            field=models.BooleanField(default=False),
        ),
    ]
