# Generated by Django 5.2.7 on 2026-03-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0012_userpageaccess_can_form_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpageaccess',
            name='can_costing_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
