# Generated by Django 5.2.7 on 2026-03-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0013_userpageaccess_can_costing_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpageaccess',
            name='can_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
