# Generated by Django 5.2.7 on 2026-03-23 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0014_userpageaccess_can_add_userpageaccess_can_delete_and_more'),
    ]

    operations = [
        
    ]
