# Generated by Django 5.2.7 on 2026-03-28 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0015_alter_form_created_by'),
    ]

    operations = [
        
    ]
