# Generated by Django 5.2.7 on 2026-03-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0016_alter_qmsdocument_options_qmsdocument_assigned_to_and_more'),
    ]

    operations = [
        
    ]
