# Generated by Django 5.2.7 on 2026-03-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0017_userpageaccess_can_approved_document_and_more'),
    ]

    operations = [
       
    ]
