# Generated by Django 5.2.7 on 2026-03-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0018_userpageaccess_can_signature_btn'),
    ]

    operations = [
        
    ]
