# Generated by Django 5.2.7 on 2026-04-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0019_userpageaccess_can_fm'),
    ]

    operations = [
        
    ]
