# Generated by Django 5.2.7 on 2026-04-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0020_userpageaccess_can_workflow_access'),
    ]

    operations = [
        
    ]
