# Generated by Django 5.2.7 on 2026-04-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0021_qmsdocument_updated_at'),
    ]

    operations = [
        
    ]
