# Generated by Django 5.2.7 on 2026-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0022_qmsdocument_certificate_qmsdocument_clause'),
    ]

    operations = [
        
    ]
