# Generated by Django 5.2.7 on 2026-04-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0025_alter_qmsdocumentversion_version_number'),
    ]

    operations = [
        
    ]
