# Generated by Django 5.2.7 on 2026-06-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0033_certificate_uploadedimage_alter_qmsdocument_options_and_more'),
    ]

    operations = [

        migrations.AlterField(

            model_name='batchpart',

            name='part_id',

            field=models.CharField(
                max_length=100
            ),

        ),

    ]