# Generated by Django 5.2.7 on 2026-06-19 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0031_remove_qainspectionmeasurement_part1_result_and_more'),
        ('qms_app', '0035_certificate_uploadedimage_alter_qmsdocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='qmsdocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='workorderpartformsubmission',
            unique_together={('workorder_item', 'form')},
        ),
        migrations.AddField(
            model_name='batchpart',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('NCR', 'Under NCR'), ('REWORK', 'Rework'), ('SCRAP', 'Scrapped')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='form',
            name='require_part_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='clause',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='is_read',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='pdf_signatures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='status',
            field=models.CharField(choices=[('process_owner', 'Process Owner'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('completed', 'Completed')], default='process_owner', max_length=20),
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='target_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_docs', to='qms_app.documentfolder'),
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qms_app.batchpart'),
        ),
        migrations.AddField(
            model_name='stagehistory',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_approved_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_costing_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_fm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_form_build',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_materialBatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_sign_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_sign_prepared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_sign_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_signature_btn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_userdetail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpageaccess',
            name='can_workflow_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.CharField(default='MEDIUM', max_length=50),
        ),
        migrations.AddField(
            model_name='workorder',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PLANNING', 'Planning'), ('PRODUCTION', 'Production'), ('QC', 'Quality Check'), ('DISPATCH', 'Dispatch'), ('COMPLETED', 'Completed')], default='OPEN', max_length=50),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workorder_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='material',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='revision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='status',
            field=models.CharField(choices=[('INTERNAL_WORKORDER', 'Internal Workorder'), ('RAW_MATERIAL_PO', 'Raw Material Purchase Order'), ('RAW_MATERIAL_RECEIVED', 'Receive Raw Material'), ('PRODUCTION', 'Production'), ('FINAL_INSPECTION', 'Final Inspection'), ('DISPATCH', 'Dispatch'), ('POST_DISPATCH', 'Post Dispatch & Feedback')], default='INTERNAL_WORKORDER', max_length=50),
        ),
        migrations.AddField(
            model_name='workorderpartformsubmission',
            name='workorder_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qms_forms', to='po_qu.workorderitem'),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qms_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qmsdocumentversion',
            name='version_number',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='formbatch',
            unique_together={('form', 'company_name', 'batch_id')},
        ),
        migrations.AlterUniqueTogether(
            name='workorderpart',
            unique_together={('workorder', 'part_id')},
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='certificate',
            field=models.ManyToManyField(blank=True, related_name='temp_fix', to='qms_app.certificate'),
        ),
        migrations.CreateModel(
            name='CertificateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='qms_app.certificate')),
            ],
        ),
        migrations.AddField(
            model_name='qmsdocument',
            name='certificate_category',
            field=models.ManyToManyField(blank=True, to='qms_app.certificatecategory'),
        ),
        migrations.CreateModel(
            name='DocumentWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qms_app.qmsdocument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('manufactured_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='qms_app.batchpart')),
            ],
        ),
        migrations.CreateModel(
            name='MachineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('supplier', models.CharField(max_length=200)),
                ('lot_number', models.CharField(max_length=100)),
                ('received_date', models.DateTimeField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='batchpart',
            name='material_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms_app.materialbatch'),
        ),
        migrations.AddField(
            model_name='formbatch',
            name='material_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms_app.materialbatch'),
        ),
        migrations.RemoveField(
            model_name='workorderpartformsubmission',
            name='workorder_part',
        ),
    ]
