# Generated by Django 5.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("po_qu", "0031_remove_qainspectionmeasurement_part1_result_and_more"),
        ("qms_app", "0035_certificate_uploadedimage_alter_qmsdocument_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchpart",
            name="workorder_item",
            field=models.ForeignKey(
                to="po_qu.workorderitem",
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name="batch_parts",
            ),
        ),
    ]