# Generated by Django 5.2.7 on 2026-04-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationitem',
            old_name='description',
            new_name='part_id',
        ),
        migrations.RenameField(
            model_name='quotationitem',
            old_name='hsn_code',
            new_name='part_name',
        ),
        migrations.AddField(
            model_name='quotation',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='rfq_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
