# Generated by Django 5.2.7 on 2026-04-29 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0003_rename_description_quotationitem_part_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_address', models.TextField()),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('product_notes', models.TextField(blank=True)),
                ('process_notes', models.TextField(blank=True)),
                ('packing_notes', models.TextField(blank=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('documentation_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('prepared', 'Prepared'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_signature_id', models.CharField(blank=True, null=True)),
                ('approved_signature_idt', models.CharField(blank=True, null=True)),
                ('digital_id', models.CharField(blank=True, max_length=100, unique='True')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_wo_created', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders_prepared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_code', models.CharField(max_length=100)),
                ('Product_name', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='po_qu.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='po_qu.workorderitem')),
            ],
        ),
    ]
