# Generated by Django 5.2.7 on 2026-04-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0004_workorder_workorderitem_workorderdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
