# Generated by Django 5.2.7 on 2026-05-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0005_workorder_other_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorderitem',
            old_name='Product_code',
            new_name='product_code',
        ),
        migrations.RenameField(
            model_name='workorderitem',
            old_name='Product_name',
            new_name='product_name',
        ),
    ]
