# Generated by Django 5.2.7 on 2026-05-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0006_rename_product_code_workorderitem_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='rfq_ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
