# Generated by Django 5.2.7 on 2026-05-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0007_workorder_rfq_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='status',
            field=models.CharField(choices=[('INTERNAL_WORKORDER', 'Internal Workorder'), ('RAW_MATERIAL_PO', 'Raw Material Purchase Order'), ('RAW_MATERIAL_RECEIVED', 'Receive Raw Material'), ('PRODUCTION', 'Production'), ('FINAL_INSPECTION', 'Final Inspection'), ('DISPATCH', 'Dispatch'), ('POST_DISPATCH', 'Post Dispatch & Feedback')], default='INTERNAL_WORKORDER', max_length=100),
        ),
    ]
