# Generated by Django 5.2.7 on 2026-05-21 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0009_workorderitem_assigned_to'),
        ('qms_app', '0032_certificate_uploadedimage_alter_qmsdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='stage_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qms_app.formfolder'),
        ),
    ]
