# Generated by Django 5.2.7 on 2026-05-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0010_workorderitem_stage_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='approved_signature_idt',
            new_name='approved_signature_id',
        ),
    ]
