# Generated by Django 5.2.7 on 2026-05-25 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0011_rename_approved_signature_idt_workorder_approved_signature_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('rfq_date', models.DateField()),
                ('required_delivery_date', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('delivery_location', models.TextField()),
                ('partial_delivery', models.CharField(blank=True, max_length=100, null=True)),
                ('material_grade', models.CharField(blank=True, max_length=255)),
                ('applicable_standard', models.CharField(blank=True, max_length=255)),
                ('heat_treatment', models.TextField(blank=True)),
                ('surface_condition', models.TextField(blank=True)),
                ('packing_traceability', models.TextField(blank=True)),
                ('certification_requirement', models.TextField(blank=True)),
                ('counterfeit_prevention', models.TextField(blank=True)),
                ('freight_terms', models.CharField(blank=True, max_length=255)),
                ('payment_terms', models.TextField(blank=True)),
                ('quotation_validity', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('compliance_statement', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('prepared', 'Prepared'), ('approved', 'Approved'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_signature_id', models.CharField(blank=True, max_length=100)),
                ('approved_signature_id', models.CharField(blank=True, max_length=100)),
                ('digital_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_created', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_prepared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RFQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('material_code_grade', models.CharField(blank=True, max_length=255)),
                ('material_dimensions', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('intended_use', models.CharField(blank=True, max_length=255)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='po_qu.rfq')),
            ],
        ),
    ]
