# Generated by Django 5.2.7 on 2026-05-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0012_rfq_rfqitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='counterfeit_prevention',
            field=models.TextField(blank=True, null=True),
        ),
    ]
