# Generated by Django 5.2.7 on 2026-05-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0013_alter_rfq_counterfeit_prevention'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='cgst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rfq',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rfq',
            name='igst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rfq',
            name='sgst_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
