# Generated by Django 5.2.7 on 2026-05-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0014_rfq_cgst_percentage_rfq_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='freight_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='payment_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='quotation_validity',
            field=models.TextField(blank=True, default=''),
        ),
    ]
