# Generated by Django 5.2.7 on 2026-05-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0015_alter_rfq_freight_terms_alter_rfq_payment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='commercial_requirements',
            field=models.TextField(blank=True, default=''),
        ),
    ]
