# Generated by Django 5.2.7 on 2026-05-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0016_rfq_commercial_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='compliance_statement',
            field=models.TextField(blank=True, default='Please confirm in your quotation that the offered material fully complies with the above technical and commercial requirements.'),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='counterfeit_prevention',
            field=models.TextField(blank=True, default='The supplier shall ensure prevention of counterfeit material and maintain full traceability to the original material manufacturer. Material shall be supplied with proper identification and supporting certification.', null=True),
        ),
    ]
