# Generated by Django 5.2.7 on 2026-05-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0018_deliverychallan_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='rfq_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='rfq_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
