# Generated by Django 5.2.7 on 2026-06-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0021_alter_workorderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_inwarded',
            field=models.BooleanField(default=False),
        ),
    ]
