# Generated by Django 5.2.7 on 2026-06-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0023_purchaseorderitem_received_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_inwarded',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent'), ('partial_received', 'Partially Received'), ('received', 'Received')], default='draft', max_length=30),
        ),
    ]
