# Generated by Django 5.2.7 on 2026-06-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_entry', '0003_product_productcategory_goodsitem_product_and_more'),
        ('po_qu', '0024_remove_purchaseorder_is_inwarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goods_entry.product'),
        ),
    ]
