# Generated by Django 5.2.7 on 2026-06-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0025_purchaseorderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='quotation_qr/'),
        ),
    ]
