# Generated by Django 5.2.7 on 2026-06-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0026_quotation_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='dc_qr/'),
        ),
    ]
