# Generated by Django 5.2.7 on 2026-06-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0027_deliverychallan_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='workorder_qr/'),
        ),
    ]
