# Generated by Django 5.2.7 on 2026-06-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0028_workorder_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='rfq_qr/'),
        ),
    ]
