# Generated by Django 5.2.7 on 2026-06-17 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_qu', '0029_rfq_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_no', models.CharField(max_length=50, unique=True)),
                ('inspection_date', models.DateField()),
                ('part_number', models.CharField(max_length=200)),
                ('revision', models.CharField(blank=True, max_length=50)),
                ('drawing_reference', models.CharField(blank=True, max_length=200)),
                ('cad_model_filename', models.CharField(blank=True, max_length=255)),
                ('batch_lot_no', models.CharField(blank=True, max_length=100)),
                ('inspection_stage', models.CharField(choices=[('final_release', 'Final Release'), ('pre_shipment', 'Pre Shipment')], max_length=30)),
                ('cmm_model', models.CharField(blank=True, max_length=255)),
                ('cmm_calibration_valid', models.BooleanField(default=False)),
                ('calibration_expiry', models.DateField(blank=True, null=True)),
                ('program_loaded', models.BooleanField(default=False)),
                ('program_filename', models.CharField(blank=True, max_length=255)),
                ('drawing_revision_verified', models.BooleanField(default=False)),
                ('revision_match', models.CharField(blank=True, max_length=100)),
                ('fixture_setup_verified', models.BooleanField(default=False)),
                ('fixture_id', models.CharField(blank=True, max_length=100)),
                ('environmental_conditions_stable', models.BooleanField(default=False)),
                ('environmental_log', models.TextField(blank=True)),
                ('all_features_within_tolerance', models.BooleanField(default=False)),
                ('tolerance_remarks', models.TextField(blank=True)),
                ('surface_condition', models.CharField(blank=True, choices=[('ok', 'OK'), ('damaged', 'Damaged')], max_length=20)),
                ('labeling_verified', models.BooleanField(default=False)),
                ('ncr_initiated', models.BooleanField(default=False)),
                ('ncr_number', models.CharField(blank=True, max_length=100)),
                ('hold_tagged', models.BooleanField(default=False)),
                ('hold_location', models.CharField(blank=True, max_length=255)),
                ('inspector_notified', models.BooleanField(default=False)),
                ('notification_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_inspections', to='po_qu.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='QAInspectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='qa_documents/')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='po_qu.qainspection')),
            ],
        ),
        migrations.CreateModel(
            name='QAInspectionMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255)),
                ('specification', models.CharField(max_length=255)),
                ('part1_value', models.CharField(blank=True, max_length=50)),
                ('part1_result', models.BooleanField(default=True)),
                ('part2_value', models.CharField(blank=True, max_length=50)),
                ('part2_result', models.BooleanField(default=True)),
                ('part3_value', models.CharField(blank=True, max_length=50)),
                ('part3_result', models.BooleanField(default=True)),
                ('part4_value', models.CharField(blank=True, max_length=50)),
                ('part4_result', models.BooleanField(default=True)),
                ('part5_value', models.CharField(blank=True, max_length=50)),
                ('part5_result', models.BooleanField(default=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='po_qu.qainspection')),
            ],
        ),
    ]
