# Generated by Django 5.2.7 on 2026-05-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_visitor_badge_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorbelonging',
            name='serial_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
