# Generated by Django 5.2.7 on 2026-06-19 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qms_app', '0035_certificate_uploadedimage_alter_qmsdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('DAY', 'Day Shift'), ('NIGHT', 'Night Shift'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('task_description', models.TextField(verbose_name='Task / Activity Description')),
                ('task_area', models.CharField(max_length=200, verbose_name='Area of Task Performed')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('issues_observations', models.TextField(blank=True, null=True, verbose_name='Issues / Observations')),
                ('supervisor_signature', models.ImageField(blank=True, null=True, upload_to='activity_log/signatures/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='qms_app.workorder')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
