# Generated by Django 5.2.7 on 2026-03-16 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='form',
        ),
        migrations.RemoveField(
            model_name='table',
            name='form',
        ),
        migrations.AddField(
            model_name='tablecolumn',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_builder.form')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='form_builder.stage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='form_builder.stage'),
            preserve_default=False,
        ),
    ]
