# Generated by Django 5.2.7 on 2026-04-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='doc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='doc_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='revision',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
