# Generated by Django 5.2.7 on 2026-04-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0002_formresponse_doc_name_formresponse_doc_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablecolumn',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='tablecolumn',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
