# Generated by Django 5.2.7 on 2026-03-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0003_alter_field_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('percentage', 'Percentage'), ('formula', 'Formula'), ('table', 'Table'), ('select', 'Select'), ('checkbox', 'Checkbox')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tablecolumn',
            name='column_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('percentage', 'Percentage'), ('formula', 'Formula')], max_length=50),
        ),
    ]
