# Generated by Django 5.2.7 on 2026-04-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0003_alter_tablecolumn_options_tablecolumn_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('percentage', 'Percentage'), ('formula', 'Formula'), ('table', 'Table'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('signature', 'Signature'), ('link', 'Link'), ('file', 'File Upload')], max_length=50),
        ),
    ]
