# Generated by Django 5.2.7 on 2026-03-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_field_options_alter_field_field_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecolumn',
            name='is_total',
            field=models.BooleanField(default=False),
        ),
    ]
