# Generated by Django 5.2.7 on 2026-04-25 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_alter_field_field_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costing_approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='is_costing_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='process',
            field=models.CharField(choices=[('RFQ', 'RFQ'), ('FEASIBILITY', 'Feasibility'), ('COSTING', 'Costing'), ('REGISTER', 'Register'), ('PROPOSAL', 'Proposal')], default='RFQ', max_length=50),
        ),
        migrations.AlterField(
            model_name='tablecolumn',
            name='column_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('percentage', 'Percentage'), ('formula', 'Formula'), ('signature', 'Signature'), ('date', 'Date'), ('link', 'Link'), ('file', 'File Upload')], max_length=50),
        ),
    ]
