# Generated by Django 5.2.7 on 2026-03-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0005_tablecolumn_is_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='process',
            field=models.CharField(choices=[('RFQ', 'RFQ'), ('FEASIBILITY', 'Feasibility'), ('COSTING', 'Costing')], default='RFQ', max_length=50),
        ),
    ]
