# Generated by Django 5.2.7 on 2026-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0006_form_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
