# Generated by Django 5.2.7 on 2026-05-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0007_alter_field_field_type_alter_tablecolumn_column_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecolumn',
            name='column_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('percentage', 'Percentage'), ('formula', 'Formula'), ('signature', 'Signature'), ('date', 'Date'), ('link', 'Link'), ('file', 'File Upload'), ('image', 'Image Upload'), ('select', 'Select'), ('checkbox', 'Checkbox')], max_length=50),
        ),
    ]
