# Generated by Django 5.2.7 on 2026-03-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0007_form_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='ref_id',
        ),
        migrations.AddField(
            model_name='formresponse',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
