# Generated by Django 5.2.7 on 2026-05-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0008_alter_tablecolumn_column_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecolumn',
            name='options',
            field=models.TextField(blank=True, help_text='Comma separate values (e.g: Yes,No,maybe)', null=True),
        ),
    ]
