# Generated by Django 5.2.7 on 2026-03-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0008_remove_form_ref_id_formresponse_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='process',
            field=models.CharField(choices=[('RFQ', 'RFQ'), ('FEASABILITY', 'Feasability'), ('COSTING', 'Costing')], default='RFQ', max_length=50),
        ),
    ]
