# Generated by Django 5.2.7 on 2026-05-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0009_tablecolumn_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='table',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
