# Generated by Django 5.2.7 on 2026-03-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0009_alter_form_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
