# Generated by Django 5.2.7 on 2026-03-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0010_form_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablecolumn',
            name='column_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('percentage', 'Percentage'), ('formula', 'Formula'), ('signature', 'Signature')], max_length=50),
        ),
    ]
