# Generated by Django 5.2.7 on 2026-05-06 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0010_alter_field_options_alter_table_options_field_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='layout_type',
            field=models.CharField(choices=[('column', 'Column Based'), ('row', 'Row Based'), ('matrix', 'Matrix Based')], default='column', max_length=20),
        ),
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_builder.table')),
            ],
        ),
        migrations.CreateModel(
            name='TableCellConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_type', models.CharField(max_length=50)),
                ('options', models.TextField(blank=True, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_builder.tablecolumn')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_builder.table')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_builder.tablerow')),
            ],
        ),
    ]
