# Generated by Django 5.2.7 on 2026-05-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0011_table_layout_type_tablerow_tablecellconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablerow',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='tablecellconfig',
            name='cell_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('percentage', 'Percentage'), ('formula', 'Formula'), ('signature', 'Signature'), ('date', 'Date'), ('link', 'Link'), ('file', 'File Upload'), ('image', 'Image Upload'), ('select', 'Select'), ('checkbox', 'Checkbox')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='tablecellconfig',
            unique_together={('row', 'column')},
        ),
    ]
