# Generated by Django 5.2.7 on 2026-05-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0012_alter_tablerow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecellconfig',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
    ]
