# Generated by Django 5.2.7 on 2026-05-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0013_tablecellconfig_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='row_header_name',
            field=models.CharField(default='Row Name', max_length=255),
        ),
    ]
