# Generated by Django 5.2.7 on 2026-05-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0014_table_row_header_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecellconfig',
            name='is_total',
            field=models.BooleanField(default=False),
        ),
    ]
