# Generated by Django 5.2.7 on 2026-05-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0015_tablecellconfig_is_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
